### ISSUE TITLE
ERD를 설계한다.

### ISSUE THREAD

**Issue by Martin0o0** [KHU-RETURN/return-community-backend#2]
## 상세 내용을 기입해 주세요

- [x]  요구사항에 따른 ERD를 설계합니다.
- [x]  논리적 데이터 모델링으로 구체적으로 설계합니다.
- [x] 엔티티와 속성, 관계를 정의합니다.

**Comment by KellyKimHyeJin** [comment]
![RETURN_COMMUNITY_ERD](https://user-images.githubusercontent.com/122080616/228366974-22a55bb6-643c-47b9-bf22-ea63f51dc83b.png)

**Comment by Martin0o0** [comment]
수고하셨습니다!

**Comment by KellyKimHyeJin** [comment]
도움 주셔서 감사합니다!!
